#ftp:
#  username: qxu1146370255
#  passwd: Zmqftp2018
#  path: 121.42.88.102:21/wwwlogs
#  #其它参数:readLock=rename表明,FTP不读取正在写的文件。delay表明每隔多少时间FTP下载一次文件。filter表明过滤器,用以过滤掉不想下载的文件,delete表明是否在下载完后删除FTP服务器上的数据,recursive表明是否递归读取子文件夹
#  options: readLock=rename&delay=900s&binary=true&filter=#txtFileFilter&delete=false&recursive=false
#
#  url: ftp://${ftp.username}@${ftp.path}/?password=${ftp.passwd}&${ftp.options}
#  # 本地下载目录
#  local-dir: /Users/rainbow/Documents/ftpdata
#
## 后台运行进程
#camel:
#  springboot:
#    main-run-controller: true
#
#management:
#  endpoint:
#    camelroutes:
#      enabled: true
#      read-only: true
#
#
#server:
#  port: 8888
#  #context-path: /ftp
#
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:49161:xe
#    username: mc
#    password: orcl
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: oracle
#
#
#  jackson:
#    serialization: true
#  freemarker:
#    allow-request-override: false
#    allow-session-override: false
#    cache: false
#    charset: "UTF-8"
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: true
#    prefer-file-system-access: true
#    suffix: .ftl
#    template-loader-path: classpath:/templates/
#    order: 1
#
#    settings:
#      template_update_delay: 0
#      default_encoding: UTF-8
#      classic_compatible: true
#
#
#
#  devtools:
#    restart:
#      additional-paths: src/main/java
#
#      exclude: static/**,public/**,src/main/resources/static/**,src/main/resources/templates/**
#
#
